version: '3.4'

services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - PGDATA=/var/lib/postgresql/data/url_shortener/

  web:
    build: .
    volumes:
      - type: bind
        source: .
        target: /opt/app
    ports:
      - "4000:4000"
    environment:
      - DB_PASS=postgres
      - DB_HOST=postgres
    depends_on:
      - postgres
    command:
      - ./run.sh
